apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-ml-iris-prediction
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-ml-iris-prediction
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: deployment-ml-iris-prediction
      name: deployment-ml-iris-prediction
    spec:
      restartPolicy: Always # Definido no nível do spec do template do Pod
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      containers:
      - image: gcr.io/ml-iris-prediction/api-ml-iris-prediction:latest
        imagePullPolicy: Always
        name: api-ml-iris-prediction-container
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"   
          limits:
            memory: "4Gi" 
            cpu: "1"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext: {}
        livenessProbe:
            httpGet:
              path: /health
              port: 5000
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
        readinessProbe:
            httpGet:
              path: /health
              port: 5000
            periodSeconds: 5
            failureThreshold: 5
            initialDelaySeconds: 10
            timeoutSeconds: 3