apiVersion: v1
kind: Service
metadata:
  name: svc-ml-iris-prediction
  namespace: default
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app: svc-ml-iris-prediction
spec:
  selector:
    app: deployment-ml-iris-prediction
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  sessionAffinity: None
  allocateLoadBalancerNodePorts: true
  internalTrafficPolicy: Cluster
  ipFamilyPolicy: SingleStack